version: 1
metadata:
  name: "outposts"
entries:
  - model: authentik_outposts.outpost
    state: present
    identifiers:
      name: "homelab-outpost"
    attrs:
      name: "homelab-outpost"
      type: "proxy"
      service_connection: null
      # On peut ajouter ici TOUS les Proxy Providers du homelab
      providers:
        - !Find [authentik_providers_proxy.proxyprovider, [name, "ArgoCD Proxy Provider"]]
      config:
        authentik_host: "https://auth.beutra.fr"
        authentik_host_insecure: false
        kubernetes_namespace: "authentik"
        kubernetes_ingress_class_name: "traefik"
        kubernetes_replicas: 1
