---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: hermes-agent-provider
  namespace: hermes-agent
spec:
  encryptedData:
    NVIDIA_API_KEY: AgBj1MaHlLJhTmyubhYOeawxb91xGg3iXYmswPDVwsbARJv9yvxb3+7a0XVpX0JPb+9+HLkBWCu8fmxrgJI/nZJ0M555SU2hQSHoN3kXelAq+V8b/KfF/SHG+hp9W7ltMsKOWOcd71AoU6yCESx/G5StoOWKbXrNa2FtcCjUnE9f4zIHOzoMd7McIZ1twT0sMmM/Pg1gHmiN87LKK+0mHo8Vy2/Qi1++pkA9+mDZDp53yvwKaMQLzQdv/g6BZsP2aOgUBUkmT0FKu3NKaPLkyprS78iUyU3K1yNLtuBGkQuYzmjCtgwlb1pw0KCjBiSF2W5X3+iLSdZif0gTM8f9dq7sMKr078nDtFAZ+wI1w3XXF19XoQttu411tYpl/f6W/dz7SdhfwyHvL6XPjmsbaWj1uCV3bEPeREl3+X72S3gakRf77RHF+zvQdqL42H897j7Z4+0qhE8Buf7f685MJS3JxCjBrO1NmHaZFVLJFQgOKx5HKRratqWBU3nHM75dAhvZIhNLX+qPKdCvLKE6BYpzBu6yYB9CW7XYGkfFuDF7wyDlQyWdwlOEWfPmOYXlL4tIvguLA0Fb8jHNNDcGlZO75aKMWTz/4nk8FuRal1wPx7w9YyHK34lRFH2Se1fO4Vmc4VrYOlwGCq5uAPkDrDipF3HeMyayeOLhgwl1wfYD4SksWax/5djfXMAAx0dYTA45TVfnwe2x2HOtifNA+DtlVTJvEB/+VSn2ShaijIQIxkHfh+ql7d/Or5xMETYd8Y6kpISSDtFumHXi3cDX0jwjXoITjV93
  template:
    metadata:
      name: hermes-agent-provider
      namespace: hermes-agent
    type: Opaque
