---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-runner-token
  namespace: gitlab-runner
spec:
  encryptedData:
    runner-registration-token: AgALvRw7Na3NObdh5XwMcXvuVWE9Rap4QWuMkje99Od8uWqbc9/8p8cpLK3UvMNUaMfaf3FQrtc/06ZLulaPMM0qWncp4BxW9TtwKAIzqFYccp3JVdNxGqYWOl1cuUP25o78xz0nr904Y9aurs1fIwX+H4FWWBNStGAqZ44sCY6z2vIa4fnIs2iec4K5lY49ztcF/NPZm11kOiYSUBGt2ik8Xg/51EZ9MVg0gozg4IXDeDKFQhsE045ymk2hfy5wmrD7Ea6MUeLP2JKZxjaQL66RCxRe8Zma5te7U3iMPUgtPVqYYb/64sNOniRctGtiCCTM5LWzEWbyuOMPVAjgcYcMFRCmteNWMCVwCMwrM8pPHjvPc6CIRjZDx7pU1ewuNKeC9PeozllvzBsHRXejH+Fi02Tt0je43k0i6B9d/sBKOVUwuJrfsKDidCXk/D9pnmsBbLGFrDEV1YjXZxGJxuKG3FJOLLVcfM2nyJKO+y2RHuTkNjYBF8+ORrcexn+RfUsrgsVRRLvJcRkMljv7ObaRK0KDcHu9ihCaIq7KXXgW8xWA82cPuvuRlZFuL3z+SY5/mWHGk1GXlvU+b1ZjMsr4vtZue4HYvuzIkB4p/IhGIY/kDT0+C3CRYW1SmWEcJ2C2VU8MZVp0OulDPcjKpwvLhXm6EORgk2/PkgWYUaQaGFyAvx+ID6rN3oQ96geHTWA=
    runner-token: AgAIBP/O8lXIPPS8pC8vTkQmpEJ6JPfMzu2JHcAMvhINlFdy1LEYTK1PNAwvRReiZPoY86d3IXPolzYgi8bRgdSNmkmLLzMrjT0k3rhB0GnXdK6Q31kLTE0BePVe0Xef//j1EwilLnQ9YpR0YcEGY9wfeVFXxIIj7/rAWTAmQgULazOO3TtE8l7WBj1a2wruKOjmFiFS+1Mo9S8yPhSH6EUMHO11ApjVdvTTR0GbnrD4NlvrywQJ23qqD+ZC0LXMDlP1FsrSRqpXWj+zI9mYbyeCAdtVDiqqcXBo1X0QcXOEUEHwyuYOXxf0p8iUXHPGX6t6N/hWgZ5mpPzy0jCcVjGqS71ZnafA9dEnkQbkPu4pzJ0QT+ReLBpLRvnY3uFhdN9+ZxutrI0ezQmOlPaeUHFQ5oa/QtUhX/lB+UuyIJsOh/yNSGBRFy1ZlRFfPm5OhkdqCPwmFwpddQyBGzWNrSLhDiN0DrSbhqd1oHpcGUh+7Wmv3SKAyDMKDN7ZK/KJ7RDxtA+gZn1Y7x6bAJbP+14Ye8luoHwz0JU8dnnBQQJYVVTQGsId4o7GkJ7Yp8mIRbNKS+H6dmETKz1sqn7xlj0V4IYPGMe0yAussoRKt6W9/c82iDOkskLmhj5WRdOr83G5oODb79LGK0oy4ak0oN6N0v6D8SAmYgcVrI9gLMmNAb0yICre2ISyBTaB/XB/JyC0Z7Wo2DcRWeH/xSLybDaoP11IAJJFpvheXI4k6e+9McEgE2ayVXAowOinJ3HoaqoNuMClqxsS3g==
  template:
    metadata:
      name: gitlab-runner-token
      namespace: gitlab-runner
