---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-runner-cache-credentials
  namespace: gitlab-runner
spec:
  encryptedData:
    accesskey: AgC29IiAtJJ2AxrD1msGxYaFqlj6Jj5aAMvMgitFPfEolqZL0tBvMAyxiBt35lJ+tBw5s1XJyIEHPeYBl3FXUj5dgJOWUrSqC2OzJpB1CieXs5Iif1aFtG/LXQq/2V1Ldi+TSHKE1quM/1eH2T5nputFOK1shNXPvWykJ8VhSvABhzJEhY/F8HdaKWtkHXoPda+K3xrjp+IrAwBSCBpxff4PHwaHhbAZmX/dB0CkPmNjvzUHF+Fx+3BKLxdeHdyD+waV1q7SP5pWiM3AcN5PhV71fmLntz7qyIb5SiU7L/yYzvWbz665NiSByRWGrqZmwJu4eVPkPD55tzVCGn3KhrqSfC8ASVhe9NC+tQHvRwtsUOoBLNUtcb4d/F6bHfau4aYklHAigk25Ku1M07PjpvWyOI139vo9dh99DIh0Cage99UfZ8xTLYM+jTcHGhKk/TElq8DW2DrFme/P8vxt2YgsaKR70HBjRx13a10MhIWqa1cggiScAcFk9wyXzuop33m+7ehPRg9agIfXtr66gQP2v4b9Bj/CqwoFW1IWZ8xicSCc98SO+/B60pQn44TnsJLGDw1x6063ceeAICitjwOs3Pf7cASWP1Fr7Q9lxnyggZajOFvmyJEVJXlxhzPu/1gOgjbtQcRaGwnrqTc8/KEw0nyav//omZb0Rc2jZh8hghBupqt/AlZKr/enPm95vYVrUpa1oCxTxwnnL/hyEFq7YhlOhQ==
    secretkey: AgBMOwnozgN9qdCoMNYlTIXT3N0PdaD1md1sP1bLQGBz4WJQVme2IseBgP69Ww5hZwG2c09c0cXzV47STPyKohS0OC2dzqPLKuFBqy3fHGrBN+Y69yuPyJXQYuij7jgVI0sw0guS1yEvXGKq6xrwLr1LgJwi/pjFOpXo8XfZ48jQxJVprRpUwTy127yAmfU1VyXycL1FDTJC/BqFut9FV5LyylZYA4h4Lh4NLbO6bPzrkxYbiZvIIgxMcAI177B8wZ5ID/I8g1BwX5er2UXCJceJjZH+zanr3CGsRbPAD3C7YC1w2viECQH6vWPO4K2FyXsspRvUTjkLf2RlvNkRkZf7Z4eevo3zQIMSCqdXoE8fNXRa3LYib/MiHT9zQBKvUIRrJxijIAil5A0+yDZQ8Euv6RVCUrcPDG8IXmZqdEggYecTOj5knz/FrzeYD+9NeEOQFL0xnxTww4Ir0kAwjUw5iZenymuhMXGPMnE6b0i+hlkPupPAnk5LuK1XzBMJIHJwJQ56HJl9vc1rnAMJEcI9NsjTn25T0eiCMW4z1Fkkyi/L8rpR95TwfGp8Lbhty3Ne82J/zsrYcAO+x6GtkLjhOiXCb+KcqWwWm9ooJqty3yyb49E8ZwQU9JoMJX2qXSVfe6K9sn+7PMZCNVrq604C9JLiK3l/umiQf92wo7t4goqa8r7jLK9Z0NM5imLCpFyDe1upes+P0BG0JGs8cWXVFlTPNNomdZ1UW3a3E6GsjDnqXB1096tJ
  template:
    metadata:
      name: gitlab-runner-cache-credentials
      namespace: gitlab-runner
