apiVersion: keycloak.hostzero.com/v1beta1
kind: KeycloakInstance
metadata:
  name: keycloak-pws
  namespace: keycloak
spec:
  # L'instance Keycloak n'utilise plus le préfixe /auth par défaut en v26
  baseUrl: http://keycloak-server-keycloakx-http.keycloak.svc.cluster.local:80
  credentials:
    secretRef:
      name: keycloak-credentials
