apiVersion: keycloak.hostzero.com/v1beta1
kind: KeycloakRealm
metadata:
  name: realm-pws
  namespace: keycloak
spec:
  instanceRef:
    name: keycloak-pws
  definition:
    realm: realm-pws
    enabled: true
