---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-credentials
  namespace: keycloak
spec:
  encryptedData:
    password: AgCvS5P5iJbJkgUnbojmgVL6ijfD/l2Eh9iLGfV+VjfDIYcY7pRDnQQElMswd8eoAPtsZp+LZgwN1dXB3+QSlN6NGHUEjwJfWvfkRPfoi5G9UnY6rjrSsv5C3EuYOrPgejxLaAdHSpTiF9ChHCJhc851KGfej4KyLuU0G8lQy3R4KDa2e7f7tLsEYRBn24286iOO0vPM4RsxG07VvaYcrzbFweRud6CLyOiHN6SNohBRmaVkBCh5Wp8EKxUs4kj+cAWtsYyPHw/AQEtXeE76ZN91U4r429Z5Q9+u5iCsWSSaga2gqlXsxvw4jrxZuHGJvRF2s+mcnEiFJLSNmxSE3/vU0cxAVzI4STZmSZrQ38dXtkJv2L+rHUFj9QXoFnDGYM8phe3ahFUR67enqL3PO7hMf2z/Hl0IHbxzUiTIgOgLi6uFghyGo+Bh+vOKeLEKAvOm74UC7vsOAcSjTL11OooBFDhG86x4x086M4Zm2hQXROhqF8ogEuZur21CY+CZTtYcHNRE4HEv9qSon3IZJLO4kGbcXNuIezVeHdnt3DOmjlYJpmNK4GseUffIs9Yfzjmh+pk9SluPMrg24+zzKujqOukOWvdTlU9LW7zNTvBIomnxDAI0I02/8uiORNYpesCD2RwShOOUPx7HfTg+5hZAoVwpvwZhCIAyMDQz2DXihECr1PWvZmbXkiN81nXXpViQxwRn3dctevvzvDcquQD0/H0SxsHLXkmP9tLFJvt+e33fTeFEmuNGIy4/573wnruyOk/q2NrJypXa6nodr3O4wNc=
    username: AgAE7jdbJbmLafRF+zGzBgEh5QoyDp5Nsgdk3dPAlSa3zkkt9HOAibq4LDJ7Eaf/I/ALBG0L/S2WDyErwNFHyKZeJv1/Z+P7yIL/w/SXufn07NuH0Hvbrviw8yI0Z4KSTP5n1O6ZRJgfXZ17KT2fOpg5zXutZUsIqVgvB1NjSfHh+5V0G5e/U7WPfGTPmflsPBm1eAU3i3cQxztcVV3Gc4GY2gHKIF5rAHieisxNw/0ZtTJ/zHxLm9sU3p3QDnhhqXA2I55SNmWEzPpbpg4ZNpvRNiHe5/V13goX09fI4P3qwe5+skl3GJI3Jo5cRgw70ZmJtqNyaRk2OgjKoJQ/+/3HnKgFkI606v88/5toCdxZC1jTnhWtW2ZaQWeGmj97l9HFTmQJtlKfJFlrlEjjOjG5wtDZ6xU/V6+9rPV9iBKUM8kWtADURJLCToD+gkIBb9Meza89stca7klD8LJScQqLsGzz+c1GahaXOy/bQ3LZP8At9wGdMsGW8VuHnL582JMzOpYappFLEx+jtwMZ+FBzKWIHFlQL1cBjioIFNDlwhWSYipf+k6W0IB2HX8ShJNw+gyaqmMJTJtO9uGcfORRABSEJaEPEEHKJzEHH6wvL29b2l/uUjRyoZ+SanYQ+BcGnRWVK3BQ1tSgVHYGi+90cMQh/tPeTVFNv5B2eFxe4XHUcUN08YzhOw38Zxc9e+VT3R6wATc9HLlY/
  template:
    metadata:
      name: keycloak-credentials
      namespace: keycloak
