apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-server
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://codecentric.github.io/helm-charts
      chart: keycloakx
      targetRevision: 7.1.9
      helm:
        values: |
          image:
            repository: quay.io/keycloak/keycloak
            tag: 26.5.5
          command:
            - "/opt/keycloak/bin/kc.sh"
            - "start-dev"
            - "--http-enabled=true"
            - "--hostname=keycloak.beutra.fr"
            - "--proxy-headers=xforwarded"
          extraEnv: |
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: "admin"
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: "password"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://keycloak-db-rw/keycloak"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-app
                  key: username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-app
                  key: password
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            rules:
              - host: keycloak.beutra.fr
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                  - keycloak.beutra.fr
                secretName: keycloak-tls
    - repoURL: https://github.com/hugz6/petra-homelab-apps.git
      targetRevision: main
      path: argocd/infra/keycloak-server/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
