apiVersion: keycloak.hostzero.com/v1beta1
kind: KeycloakClient
metadata:
  name: argocd-client
  namespace: argocd
spec:
  # On pointe vers le realm dans le namespace keycloak
  realmRef:
    name: realm-pws
    namespace: keycloak
  definition:
    clientId: argocd
    name: ArgoCD
    enabled: true
    publicClient: false
    standardFlowEnabled: true
    redirectUris:
      - https://argocd.infra.beutra.fr/auth/callback
  # On utilise le secret existant dans le namespace argocd
  clientSecretRef:
    name: argocd-keycloak-sso-secret
    clientSecretKey: oidc.keycloak.clientSecret
    create: false

---
apiVersion: keycloak.hostzero.com/v1beta1
kind: KeycloakProtocolMapper
metadata:
  name: argocd-groups-mapper
  namespace: argocd
spec:
  clientRef:
    name: argocd-client
  definition:
    name: groups
    protocol: openid-connect
    protocolMapper: oidc-group-membership-mapper
    config:
      full.path: "false"
      id.token.claim: "true"
      access.token.claim: "true"
      claim.name: groups
      userinfo.token.claim: "true"
