---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-keycloak-sso-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.keycloak.clientSecret: AgBVueUN6OGMBpX6+V/QiMzg/qP7bSQZhBWwwXakT74ytCwfWaL5NMRfcFZBn4dOwypt7T0uSLLfr38FYMQ0bc7cQkY12qOwwbGJ3L4FbX1eln/IrkLtyS0UuQ238iVnsRSZA4eQckl6KJRUI8KNiOzTHYEazySi90rbeVpXURBoCrUL51nOqPK6zjgrcDchEGrYLaGIpno9KdKq+r22DiiRqLwlCM6jc1eqGO+8Ts4i7dQAxZrYr1lQr17xpHI6mxREPRbLwOTkNYeG3xKlt09KEb8nN1te7jRZHFBye8ROy1ccUDwSaJMO2CgAD/4d1nEYvzRwOLY1EnkGBpwacgA7/3ka8iEOVf7sVLxw6gvubGeolYJ5JVyeEr5YO+oxkc4kuuqsC5m8S152Es53xF0Ku9R+SVNK2ptNsgf9Xs/HlEkr74QpO8i7LoUxk7p00leuuLt5Q+zEYIyje8ldWY6ZP0x3hCU06tTDeEq3G9Zf9WRfUpo+lvrakn+o3lg5eJvV0bNq3wvnCva+Kk+DaC0JeOhwd0NRYiP+1gIAcEPE7wHpfUGB1QvwEwWfaUQKIt949Tv1i1hDM5wx3GJ8N5cinqUtK+eQOWZ7cB/H4qi9a1ffwFCssFtKOiKV9nv0aT+Ltnxx1oqyzC8EfjnVBby0gocQHh0uP5dGDXoXaocxnryrmsGyo3Kt9Uv4TeDDFCou0Qbs+Wu05QlRG0jldqSLYZsYseU6QBY=
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-keycloak-sso-secret
      namespace: argocd
    type: Opaque
