---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frp-secret
  namespace: frp
spec:
  encryptedData:
    token: AgA5b49Ah577pK95UdLQkbPqEISszc/wcy8a3zTkBbvuw0/dfHm2nNHD4fG7z2q+dlu9q4sx3OMS13VyeCZSUBj1fOHzC35SyIlBRFaZM5lMYth93uZqsffWwJS+66oy3lYigkWKhMKdg/aCLPcH0akfMKdhtjyhznUSZc6bFY0Bxl3BN5cVVQY/R/BEQXu+xmCfXQFBNxro/v961d3fYJtxJc55Ltc9BWH0DgqIJP4GFs3XFzxKiht8N7Qgs9PRbqeS2ZG74UZWBWLXf0+cfjEI7WD7uItAXc4LdauLWdWwZitLOwmLP4ATmbPMV+X9X2XFi8tctjNBs7u6ea9yoJ/oUANIR+s2WnVERj+PiL/9M8jXktNLroUIM1Z9kxv/f5fykWChbsvxAb0m28edml0pTTbiOOz0ALkw4z519ADJ0N8RlLcCyU52iyd8L2k8J5rMfuvLuoUoiifHOfbRwHtZr74qralXvL7rnRnX2KH+UCcdENcP72pi5KlHTGrNRSXnl6jXWl8pEBpu1dnZUZ6DcBEHB3oRu6g5lP2ztD5DpGmIN7/Y+V7i2bihnyQq7kuw67YGdK0eq+wEs4dX8OKpwfLW56eiD1UXlonCcMUhQ1zn3BOBUM3BT1I4N1PDw+XTiXJXkpLmJgpWLBQeMu7tzarsDGYqBP7PvaksmPn2HEsrsWZbIdQJJYABQ6lGe4AvMBNFrZTLGRbzfmHKi8OD5Pex39e+ivy9Mdpf6VDs3jdVdRs7gtqxQ5kgAb/2ElA=
  template:
    metadata:
      name: frp-secret
      namespace: frp
