---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry-storage
  namespace: gitlab
spec:
  encryptedData:
    config: AgA3OwIvx14uqikUCI529e+2r0P/5B/edNc0UAnbigQ2RYBhWe8Cyl8zmqfvCy3pARlxN/Y65r40ZpCJM9H67+iyZbE3gqd3VeALwn/VxNI1OzjYQemCEJ3JA+7oHVGL+xZQcW6oCEulS+qokyRr1EejPSV/l2IPc7NKK4eUA3blZwSp48/rCxVmgIgIccfa9DHV/G6WHeYrMnDvnne7sBU3wFTMI71MQh85CP5mIGo7KtDcP+46lQd7UYRhO6TkW6i2IGEAEg7kxTqLGQV8EdsvDwGDWg3TZPoMqtwOfq6k/HfVyr7Je/+UC8KmBs71AVuNtTzgNzeQ8YrKYv6inOl9DxSndwscHB1IP/VZILdB+FxfZUGCHyoIneoeDovt6Tlg0pG07hbGTqSPvbp32rXpQvV7EP7KlojZ/uLBP6BHuvppf+tzXIqEo5qX6bcdxzBElGI8HFDxmev1Gag9H4021xP1RvvB4Gk1vAVvd+FrKxqpNboMO3IL9uBO+s/c1F3MZpAU7Stpu7lWp5XdabPeZV6npcCydJSVfGFARVE3JanTVO2WIDuSMIoMiFGUXU/qlQaFROX0u49YF72Amtq3UmT8wAEOdryO3ZBgpcMoqo2YYzfEo/hzNnYc4Zfj6C7eVPRP7TABChC2CUXbRQpYMtuPfegUbH5KGlEqYBL3S0lB7YC1RSrLDeHkv23S7idWry/sBrSwWYmNQ5N7I2fyV5mLHIfz+hbbvOi/51LsfimIIcVCZ8jU9SKOfjeQjFueVIWX3oett3I/0L87w5nXN6Itw1GSCYE4lmEZ4UKvgoG/ifE85OOnoIPXq+m1ikJMRCOaA846H+ElBKOnsTqjhbcOzlIhmyAYtsdIHuCekCfeoQO2N4kMPOoCdQXJhXZ40TtvCKAVZTC6WzzjPKz3Wyu5+qzH5kHhRvweoO3h826ZEJy90CpP1dv1+0EPLLuN2n/QlJWAv14ShzP+tF0Mz6KkirPavTGWWAEUq731tIKyV6jtKHUIWuTRd0YIAium
  template:
    metadata:
      name: gitlab-registry-storage
      namespace: gitlab
