---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-minio-credentials
  namespace: gitlab
spec:
  encryptedData:
    accesskey: AgAa6IuPxKm68xhSvvKTzGYg1ztHaw0wrCY2b56ihoNmG1zed+crv3jhAkQNCAUVagIMZDENXCJnPF8zHSL4/ycgcqgh2FKojAHDnhXkbzsBf345DGGPQK0xVlfdzabNpgfkUHNS1pkseKf0xjeIH2f4PWEVj9N+h1nhl4sBsVEbeaDUHxNDUXPtVQn+XdJsldgExgAYQmo65N/ZBEL/h0C3nQjV9RzSPEvwpJPdByDRYrjXkahCKbDOFFCmON17fqm30X03xGb12OQFgH9K2ruNgIIExRFfPGonLYL/P4z7BvDglks/O8sp244DrQKwEhnn7ZfrHquLDWO6wfMaloaWZ4j8FmT1V/nOBk7yYOS1ZJkYQz4rxcB29c0N5vUmCjvc+HNK1PKl5OY8sm5O8eYp5j1vZbdca0pUV+2c6Ibbg3/rfb5Vg/opt0deUZUyopXBhfV9LpiXv5Ys4eSrETNdn5ExC1sXkw4ICLkyGNZYLmz7zWSh6maQehT5XgcjYr1G6yl3Zx2eUDJApDiDGP2pBR4yMzjebQRmrxK1DI9tWXvUM9i5OonkL80BmhFX/MXGhCi5tGS9GP9Rwc/Fy97ijrpb0IDhy5naNwdPHiYYNGUp63I16QEUugd5Cb86UdAD8ZEKF4M6Vn64jFdJ+s5wETTiJ8dNucCYvPA/1aziawkMF9/cZBoVXfUA4tc1TvGWsX3YF8D5LU2Pw1pAt4hQw9Us4g==
    secretkey: AgA+mNRtSJb2mHuwpptETlcxVrd79LVWzRDHCZ5FhvQwyznhdngtVEmYhl13vNGrsLrtodUP7Z5Kep9A888WMSOSYtT0iGbhlh6hVzdOBbelDCnsfbu69wqoKwgk3d0GhdOMMuB2EzLnyKY477BLpaJuLNPKGxZiUA/yvSWs5DxWyo4NsvTCnZHw9Rfqa4KGakacfoCARFwMHjtTHDX1+5ZFKarzo2N3fNJtdNg8hO2jYBBWqJpRNbX7PcMzZQV04AzBplTZA3tCmNFEqdVnTlnvBjY3M5R5Tc/hm2oHpWB6/FbFgBYXroNibo65JqFQGMiXzmtOUpxUYpWtVIDfFRjZhUGpEiGrrsUOOQSWUrq3vGgJjJN0oDP+Ba/QaiJ1C4s9rIuGqjqQp+ecsjyUET6bgvrTO2o/wbjOfT2J6HHYzyNpoXXHH2XvYDxFYapilH8bZHSv5/+c6PdI6+F09Ke+ouSQzba0Mc8NYibH5P1ndC6cxAfqTkIKV3jTHICXvifuSuENs6mW5P4h31MQRrtg8YYzh0Z2v3RbXYZ2SJAp/k903hrDZjf0UkF+WtgIFhO2kh+HEIXFqhWwhzpv7lwUm0pCOASZpPo8YsKnzK3H1M4oV+jAE+wvN2FFalR3gsZ4mUYZprBRrgPvyXjcnlan+3gDt03aUeaBQR7ZuV/+rBv1p61F47lsG0VvYP2aQKendR1AX/ZtoowFFSBYLlG/6qtuL8koQ/CUVzdqqhfenI3K4awv0nZi
  template:
    metadata:
      name: gitlab-minio-credentials
      namespace: gitlab
