---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-object-storage
  namespace: gitlab
spec:
  encryptedData:
    connection: AgBq0gu4K+MlnX+Tc41ERNlV4FJwv9r7HKS/CcNjz/nZAAom1UsR+KTx+YYrmGd95SF44T2oTbaqDHPEmC+w+zlYXR97ktYlAAB9t9ZAalO8/sCoXZEX13DxzLGqLHI5ei84WzBJNR3PcqRyUQUtaOryrI4y0gFY6pJhGJuuJQ5JSlf0ct6I2FQqK0QMS+Ab+gn4UeCW4RHdJQGzYZkIv8kjZF74WgyuLm/cwDMqEWiCfGtDlQfec9a/xxHY61tBkTvKi1jvqKJc2MeGu9lLWXms/iKi61U6T2VQWiQD+aS8bGSsoXzj1HMcGsGPSLmkNtFLuxLsQ1zvd95CoUSNeUFQ4BxLDUC265Nx6BApF034R7C7GJdbojGiABuxv+egSS2IR5szw6Loi3djXC28f+8pw1Ebe3/n0Rj3H2qPUEfmnUtmFbZ0JmG9RuW8Vf2MeaT5gr5plzdFNR0cAVTLZ/jW5cN0doIf3bhBGJD0YBK7CsAfSMEqAGmfCTtS8Qh2Xz1B5rBWbwSVTYIKuDYm6eMGCJC/Ji27DVXe0WGG5qdo2FFH5s1NsWb9ugLdQiF5LpUYMnqbyFO0ax7IuhRSlIlEcwtKwVFYL4GdxcZHDXhPZ52rXSZxLzGSmdjXhP+Q6Nw3izU2Atri3rtHNObvBCb2YBKGzUK5cc/ZCRhDbRwOCaRugnksQFJ4K+tM0OabuFp/6RrVSFQZu+uySeYnHuYmGDKHuXK1JS6fd0WFCa5tliXAoMZHTiEcjO9LfSfBPw0o8jw9/55u1bfWAE7wXBVKkCpBq+dF8Z5aR9SzGt2T7cWC6ZPchNxIC4Z29JifU8Ty6of1e0VS1fyyAZ4nJ1QMmQYUWX1EqV+9NFCiiATLV7+UeNSPoEQ15uqGlgMznn/pN9jXr4EqbImCuW1vTzWS9PIs1yWER6+Shtr1q79uzVuS9ryoY/QZv5qnLp6MwV9srpOqrGWcdCZJtG96aFfKcAO5UG/tP48cUiC+rqkOQdHbRvffqearK3TL56aSzkE=
  template:
    metadata:
      name: gitlab-object-storage
      namespace: gitlab
