---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-oidc-authentik
  namespace: gitlab
spec:
  encryptedData:
    provider: AgAA5pen31AXiUo7FSbJAPDzH+HzyQTSf10PhFYoMba+rIBsgddAp2p/FLpqqV5L/0oLFRkkY+Cck7gI9V8AuSBLtLIrG44XDmdxy+yM3wFHEQWNlD8awA0SDvv0yWSayQi975eyRSPLsyqBRNCw7sTaKseyfPdeEG4sfyQiHapTTSVsy2WgD9kRXXhZ3ZSZSdJgk910dE5nDcBNLQXZCfA9BXIXanz5EonFh/+WljKKXnN2hxRHrrFnEg/AIVse1wZRadOL9dXmeFgLxaGkK7tsgUCVWxZK3/frGxQUEZP7uIZh2kx3e8XOcd1go6JG6eGx2okZSUavRNLYFLlNPrFU8Hkm1QRt9bOXJwsJSqW9iPvvPEPmpibXK0aEIoEYV59GvFsMgDIfBvaZ/+2LFJxOCycAFZQVr+DYa3Z9iRHvR45ywnc2zbfvlyJ1t5Q40nH4UgUp43ehQFDT5OxeajoETeMYksU+wHsfYRMbE0jVWCBErPIGzmwGQt82P96d7pxThpwvJFGyWOFIZ7VHRnt7tx1/dTXjGv0yiCIVX1/ShaPEpgiTv1zX7H1OtbsDkQdBqejnnBERc0tv9mUW5NNAsfSasKEg5SROVKv9Yegwd1PzyAA5QhyBF1IwFrEuKOxuCnnHglUIJtiPJe60D2phE8k4po/iVwY8GcV82vWbg/HMElyXwNnp9INtblsucy+29e1AL9sbI+pxuvgptP9n4xOdpy0LGkvm0aB903lAaPTSdMkHKzislNMRPr4OPy2zmAkwVO9WyeMC/OIjLPb9V3kWwa0+xHmj48xPGMNIOQW+nNHiLB4LMqZlb7o2C16uXCYpNIXyYP++qgr4zLzbCJ6hwsuFzDV0ekFE0Nf0fJtC9j/1/rV7b6U+N10d1kIXCpJVkPk2Oc4K523m9BXX26xNbpZGWGsUjq+mtW0tqoLTeIxzOgMEWeL2FOwZN0oZiLEymtYc4utKeym9z8tW+72pm+kPFenh9zJ9M2Qe0y4IV0RbbApwX0Hy7rDmrWr8eJy6Jjn3weGX9xyOdZxB9/H9w5mRcoyGBR29xzRcWt6Y9Kx/yuWxCVaFT8moabgQmW2PiXd2aFMkj8zcaU6TyHSSvS9nKlwrfBG96mHyN9wR/YsRziF0DLz9u1IL2X1SAoszC75SXm/soMxWluShmtdLT0ws7NLhzBnisdkpJei+Z58uJ/a29uR2REn8/8onDWbFinMDfLktmwPSjOB32AqTXH34wrBC6wUxoyj6xbayOgIIAcGIUdgMl//fuPg0xXoJy5OcNYDdc9e0Rj3UlG0aNzQJV4TO/bTcrIj2GKcYQ3Aq0igEvZ6R9UnJCFCLXOlO92rVFOlTXtiCORfu6qMxd2rTehRZwYt2Z5fY1Sp40wLAUhnbOKUQGJ0=
  template:
    metadata:
      name: gitlab-oidc-authentik
      namespace: gitlab
