---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    # Must exist before the datastores (wave -2) and the chart reference them.
    argocd.argoproj.io/sync-wave: "-3"
  name: gitlab-s3cmd-config
  namespace: gitlab
spec:
  encryptedData:
    config: AgCBB0HJd+gihayZIRjp/5hHbGFpfNrC5RQ++z2kFQ/Xeu/DvTxWfRQ7hStXAdyDUm4fsCDiYXBpPpiwr/l7kcoiRjllJKs/PKLjVxbkQqipPSkWyxSk0NZgyka/ChmkW6Ps+zVY1pxqu0I+nE2gNINx9VTku9OvTDjpzk9zIlN1YZohyw3gUT0Kkrjul78YeO2VZfUMSsbfDg5x+zCUm9zviUUsjzIwYxel/kCi+lLPg2IYpj9IroeOccoNhS4n0eUzllbSHvxaWD5X7ns/xDAL27vFfptCFtSPNtpxmaW8rnPyzjmFVTZCbfBdYZPDnMiuorxaQbRPIPBAl2xPsuhiQ2da3N2Ex9kCy2BYVw9fFG8JbySEDMAgGBmRyGOlRjo9/gDf0kOrNV5UvEkTH1iMrYFLgV9BFyCkUU8aoq3QxsiC2Hbnb2xc2sojK4lY44WQZsMq2lS3LL7JiezLSBYEAJAhA+sB2RkUzArYColDROvndFBvdkHLV7laqKKbdoxjNqBbcThxJm5GzjZYTN9duLpV6QsipXpa7jdeRYSIr7KRZtNYNqmH9mjHtQGOzUGa+aI2RFU+0zRhU+MvAlZH8X5Lghy4RccrnIxjaMope/XUhKARB2XOmB3Y6Fur4FMagkvrswwl0Ue+k0np2G6f2WVWBV4hL+R2PzjeElvCevkANcFFsza9Nciv8ewFrAFDX1k/ftteq2ADQDzaJpahIGBPVm5Ep/2Lvl4TcFkWfEedwxOHOERPC6bxwgzLyNg8PTqi3KYagO+DKQsojbPgMEqjh7DsGWdL93kl59rRe+YBNKtIb33sQHai9vcn1UM435b3nAUcpaaj8bQg2L6EnH23NTsfMZKIBq7iERQX6x3yFgJXnJ4nlL1wk47t9lMEkkc7yxzvJOvTjAcAKHIFwNID9PIqDV9qAOXM5UIqv1fIN3kiuW1Mr96HbRZhH335f4JWIJXDKyU+FWRcU+2uC+K9bodJXUlb+78yvqLhi/6AxzHRfE5zRbhqkkog8OjN9mxQK+Y7iCp3dFj3CqIrDIE6wSCgmPOlZQ==
  template:
    metadata:
      name: gitlab-s3cmd-config
      namespace: gitlab
