---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    # Must exist before the datastores (wave -2) and the chart reference them.
    argocd.argoproj.io/sync-wave: "-3"
  name: gitlab-valkey
  namespace: gitlab
spec:
  encryptedData:
    password: AgCXs+lFytQ1cy0DxUgod1fgh3jH4hwNOzJ1CG6Df8LSminj+ZPk3AaRdUQvCXAq0HHRLeA8/bZ9oE5vNoBGrhCb5upXS0iPPwSiGPMtJgfIoQbrMzLsy2AO3mHJ5z6pi2SmYd0azIg76LsxTtpEfMUFPhfdxZ7aasa2yjCD42602chf7h1zYGCGMLR37fgADrlIBtc56HJprithVxAEJThpHRyFgrAiluhAJE3sAE8kNJ5mD4Osuj7Nvs1A6IgJMF/s5MHKw4+ezUzOI+p+cw0GGiz3tyT4qoMgTEVwAUBmLaRn++vSv/36g/P/7KOPAROvsPC8JckXt6YmRJX6NL3X1p5Yb9fvgUmmTiQBGQvVNk63z4Y9Ireo0BPrOL/e4KiDL4g2b1A+Uynp8lgIUtaOIYX9HMveCd4DXzaecqd5FY6KP7dgMAWYNy0auOw/yfBavV7AwyDXbspnWNsVitj6UC9UgGhe4ou2IsPjmPR2jgi088/hDIxxKOOOJ/BbIvCe+8qaKlCU+ghFR8hLAKCxCfJqjfuGeUiqIA1cRvdpMVzShjNX5M/+EQkL5QKQ81WHMIFNW2jvKU6A3mNVgKyDC5KCtI2n1o5KrS49h/xg2IaUpBE2RhRCBF64XBK7AJJlJa2QTFruYMuMiYqiZJXEQf7dUtnRYifpmkeV79u+YccD6E+VVLsXto53v7EVCEQLJ3VVz7XwboZAIK/8LcFgcYInGUDH9zpcKukHCVry6A==
  template:
    metadata:
      name: gitlab-valkey
      namespace: gitlab
