---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-secrets
  namespace: monitoring
spec:
  encryptedData:
    telegram-bot-token: AgCNlucIpEh3o7AGTQG4NoUuBOfz4nM+hEfQN7o0ZqCnmppvWeV/WAFd4erCFckCi8EhYdnZIgwBV0Do02yuYmpDwoTsnhJsdGhwrRYLC0VQyCQsaSPoKsMQI+DnBd+XWljmopFpVTq2mJw6ShkwZP3tg3MVbtsHLPyuYgG+bFcf6WYkhtDrS8L3ph532lDullG7d9Il5cXJAFiikxMUNzjOG898NZ5u20DgmCLSGOP5BanmKDJpvdLw/86GepDMBBoeL5/r5wjMEMugYH7E2mdMbe+9LKeCNBZyexGCmRFtpJ82cfEfVkMFvDQT2wpFf1sbs9LyYKdgUxkdh9dzarCzUDZhkghY2M7z9MWnTLgfU8K3hkyFgAso4p6xULg1RLgVYGh9i9DVysxID60PrpnmN+t3DTqMA4+gsdTqkCo9fgoxUjqnDKWLG57qescWh6hWiki9wdN2TmJhC7w78L+HnBbgKVh5+ycaaW3Kx01tPRpPdd+YO7gOj/+myEql2tmBlYEAm/8DmtC8/GM0pqrML/cpF5ivWbGPzX2SOBoEVCW5YtNljQbo/x9io1pI+fbxv64mWQkEidEXfNfoByw+gnWwVqMtViYvmSjssQgED062LN4nAbj/1FO0UdCHkVa8W1br9mAUpsVTQ0MIz66Qi5S29u0xWfnfa1/8Z8WNjG4kI5DSXcZL9Cf2GoKXb5UKEx6DLmh9oRx0+sOUvL/PAZCEE7jV90xa27YWD11zFJPHV/IR+HwzRPI6IO54
  template:
    metadata:
      name: alertmanager-secrets
      namespace: monitoring
