---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-oidc-gitlab
  namespace: authentik
spec:
  encryptedData:
    GITLAB_CLIENT_SECRET: AgCC/jes2u1q2NCeUeKEW0h3ztDwTQHza7rzqtGOfxwEK9fmwjHW5vb+m7o5MeEhhSDvHmt1+tn5sFyv5gDryT46kft/C9OKbW8MfNNarW6dpfUXTt9SVUVZDJg9XUWLHbmDDgUitpPb/8mtThCO4IfNjojhIn+FMfnxDcgCF7/PHSq9dm8VfAtKzTX1gAvrxjvz+lYbhnSiNXXD7bjK3v01Wotkpvlr/XW8moMNOut3X0OHgaYlONP0ntq1mpi0WdW7efkUBEhBbsTqwMqDlNpRUxOVKvkaD/b8eyVrw3B29hGCuvqgCZLswgWi014Q3laoZLHnL82K1Qql/SLpfufX3esG0EiYVK8FbfOcsMx3hpo657syIe4Qop24eDbs2T+Lu+zmcMr70pAOV6Iv6T+o+POlGMzCYyMvN6d3HVTQFRRQe92NE4yh2MspDoxN+/k4nqb98Z/Tqand6yCoByRW0PlqrsJDTmB9bdsjcZD/UDi34MSVlAb31N8LgMRxYyZyVS4BCziTMNhDCggjZmkFwJcavCnBvful13MsLUpAq+yZhOVeYw6PnKd9qs1PPqrCJ3v31+S8igpEva6REb4NUyBhgOxreAkYrSZVMV+hFbKgbAq74wXPbl14DRDEKOe/P+ROXFLfchfWO/etzlzp7Bj5a3qSY70mxZLt8Tyl9FBODjU4/0St2LHlQssz837tONpd1/q0tpHFzQvZa3HvKhuIR6LizUQ9r9rwEHUj59hBMPlDDUVw/YwvYprN3utPxQ==
  template:
    metadata:
      name: authentik-oidc-gitlab
      namespace: authentik
