---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-oidc-argocd
  namespace: authentik
spec:
  encryptedData:
    ARGOCD_CLIENT_SECRET: AgDENLaT+WUxqEhrMTcr8QIjI/TZBX67xTBdjZko0fvRc7aUsE75MxdCkJojPM2M9EtS2Bwj0cNlspWehCLbw8VZxlpAitozdVzRfng5deuOT/wxc/C0r3r6L/i/CkyIG/ZFA3pTbf4hWstCMaG6QifGxdiDWJxdpbkijDQ8ap7mBMExrBAe/nUDFmfhA3XJUlScK3RV2qOSyP47dMDLfDlj1KTfB6YfpuHad/IEG/jYUfiiJqIJ7jGfc0y/Gg2AKDVvf9BI64jbatY/OC6HI4qX+G+TBB1YV3ALv/h4I5cKQj8TjhewHDhjA6MvgzkE5BH/UjuB2pyYL/aO1YPdK0ePr1JeWNIYwPNcecx80Z6sOG+T/4pUkQLL8McbNT2CLcsNj0iJyEceAI0l0vHEnzUQKLtCBupwGQI2tsg1jYX6Kdiux7bYSo9Gq/lIqMI25GIeikdqUqIuy86Tia2pxTUdIih7hM98W9Js3v1kTpWwz/F++d68W5Jw01bz8kK59opJSN5SUPTZTeOIv2ouIAkZn/+LiVbYYkMZlR0zn0oX5YLKwiWdO0dvCVMaNQMH5sAlW76a60aHQw9hQekyb5kxmH/Ky/S1ZKUfbspHV3QF/xRP7KvfodKFkc5SPgwSGuiyrLXB81ky7totvXi8SvCRtxo/GpO8JRIHmyBFrgaa9AjtBvIt6CTcjl9NPE3VymBEc9aHPY0ajnBS8UXpbuqWxnvoMST9EJJAN8mv/04oA0ng46TigYr781pKP3yAdeU=
  template:
    metadata:
      name: authentik-oidc-argocd
      namespace: authentik
