---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-oidc-grafana
  namespace: authentik
spec:
  encryptedData:
    GRAFANA_CLIENT_SECRET: AgBkSEtBnuqqxUw9bprGzKQzqHwkOBu3RAxxNLIV4LtoL7qiQmvm3Wze9MpCJ6fYpg1wECVxVXFk4VGFMSmROAoIKU3QMePYtNzXtGTiU9t74w48lFjXifn/S20+sm+efJPII0mg1kJ+C/o94QrdLB71caoW9o3Y0ZVynGN7DmtYkZK4tupD5l1mWufwE3ifoaH8pEQ36iWU7v+bG1BmmTIYmmwYKx2nxkkFZ0fKyf3GPANeHXiEbPFd3ofSZkdEJx3gyZ+R1ju/gTSqH/knGGAFJfrGxmYXgmem3UncSthDVdXGBkGVtbEZM4Ova5MlJaYHXyWFXjwMY/yvA+2Fv64hqr6ESRj4HrLQzfME96zWwvMmzR0rMifWHtGuq08ACVB7VB0v95m8Uz0pyHx+N9eoDk/nFc4qfkIu6+693Kma2TMTn9kPDL3QOsMSNmAgjn8HNorhVVhNjvZ3M7Ct/H2Dkkho0brheKIMWkUdEndITPRCKbsS17jaZI+XYJnnAz36aASYc2OIiAxe+CAxlkwuvj4s97+UED7XIo3/1vHBBtLdfFWSonkxPeSzpTSNrzM2732k73Y3ozx3cjSQVVYNHzSIWV2aDEKzJycgjqtKYbH/pSTyuUo0U8BGamZZyOXB0g5rwTUwyIhy4fDntezgtYA1cdL/Dt+eUK6/ErRTTrrL+5Jnv+iwMmFs1GYV7yd74w7Lb7GYPRDT58SiXnBNEoYb2fS82W/b29bZEh99JWO/OZfOIVts+VXW60XP7Bo=
  template:
    metadata:
      name: authentik-oidc-grafana
      namespace: authentik
