---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-oidc-argocd
  namespace: authentik
spec:
  encryptedData:
    ARGOCD_CLIENT_SECRET: AgBWFylYujqIJl7lJmrIWKwTNiPmEeyrwdFnd9b8OXT2gJB3AUkG28pRBXEsWrroqiLRExOs8MdFwcLMs0WiH7acdyLKbZ9L+S+dN99YjjEc0GSKTVhIYPoQNvWGKHXiJ1olVUYLve3Vi/yaEBPCFpoZ7eTVtuqHBlMLlAct5W2dbYsUU954cr9zRG5r7LC3/aHs38L1u3cPMBPUmoOv3dQbAmiACnmI6+GYv5Bg3/IeALw0qxv9RKf+RmNr+5DY8HpDCZvSs/B/VPBpZ5HOUuKaJ58OQn0r/x2WWHU9zvQzBM7KKM0JEdg8U+k4LcHoALO4Rag6EgUt+YI8f20ReZ9f0luFECTDAV11fQlHiOIgWz2jS49F5e+XCvQv83rQwErgGJzHEcMZJfNboE97SPU3WpHd38EBGxSE7jOLkPx5GdEYJLH+J6V4OjfBxnTBs/vZYDXGXD5Q1pmzU3UtVl5/pm/rQKG4+3nETuir1Se2OEILfAkGM8pAOm67Ax86ueCoukSaxvHgZrAJ6m7ORqt+omvp+wxhLUagnJ9WTNAN+stpPTapuAsNeosDu87WyE6xMBBN42zLnkqCF9nRHnXSQXuTLtXkRyKS10K0mI7bgkqmoBnwj+gtCmDAA6Lb0AT7hvdkObEp+7/sPDjZxvneEINfkU7HKVxGvT/3rZB2MiwIIMoNI1cCwvCMyQEJvM1GhEAzv/ddRC2/2qcbhX4JokiQgvLhs9LcDfWrFYL7y0kT1Zs1a8D0oN3yyA==
  template:
    metadata:
      name: authentik-oidc-argocd
      namespace: authentik
