---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_EMAIL__PASSWORD: AgAD4fHAFWwOyx9nTjAxQ/KIPIl7hp0+ZLQDCdvrZ/ZH3+P6YUiQIW7gkm+iQP4tmMVVvhawvKe8jxWYYy8YsKtmEXWbWcXK3L4BtM+dYzZ2tfHePzxBguDlMYRVPjMOqccODgkPpKr8jnnY/FCU5Zz+X5fMJnlz2jvQoGU0voLHoyywI4gB9GC/VT9eAgrgeciOjLfAAZRy3bezBS4xs0f5C9brtdWUkhbkHBsgqp5MaS2GUVX4gqnASC4MlvqWNqqM9wxyKKiAmn79mBHY5lCJVAzfcxdijm3yd2DqJ4FzaQrnOfzRY2nbcEh4Z6NoIPHFENZfq685XNn2hsEDlFdAKrmcwofXjaSy/ytdaBZYxf1YRHA+X3Umfk5A0PVxbeYjOUALdVyuQG4ADbl6UO7gtA5AidyfTiJ5J/ZUnxJuyTpW/vtqgiLyo4N3LKPBHfc+jukDs0TLEoL7ulXL5bM4u7rhnUnoMd9+QRpVD/OeLvwV0qEjs/86O5Fm4Sxb2clVMXjgg4ilOYF87w9PmY1sLMhwUB2KNU4PS3ajdJe5VfdXV4JNvtLUSB4B9Gvxn0U/edpiOAELVoZEu+Pjzn+s4yWX9jkDQcM6S22T03Ntk9WJOoK6vHCSoMka+bHu5cqM0DhgrJD1k0rpLBoOU7cw00GTF0K1kfSkinp8ArWJXF4y7nIrv42gIPRQ0PHNzHHGVG8tgbNV5eEseNMmr3mOw47xmrdQtcK08WtTiPY=
    AUTHENTIK_SECRET_KEY: AgAMoy56ejU6DzE6iA3YFN5s/860QhzEXPSK/qT87VP+w2Wh2yRoCzUdxMeQIwAH5du3K/SIphQDkSxHSl9bk1XZ97DTvqP2e9SmLUmKLFU8SNu0B+JfxYVsihn72r4TPbUQXT0pQxPZCg2I9nwjAs05ZWQo9zej9mIoA8LgF9FN0sEuKrXsnQR8L8JEh8+9zX597HgkzaXnBEvsnb7MeF/qZnBWtMo49qkjr2SbrFinyoRZHl2yQyYrnoB8libexFo9V1vbs5P+PU/bWr1NavdEBcD8lkETC6XpaTEC1Rn5j2mjDErG5zkJUtQ0NbCdGDYwWxXx62RGV6QiP/5O7U3yw2gVojh1iC9e8ZsaUMr7KfhvNOVOleQjLsZ1fG8tNAXl8U+F9f6Uxrick3W4pJqgpTCLCRvLdzq8PUMuroVUFeQSf30XPTrvw4wzsDB0JVlCxyuamjh97bELzmG5iMdTK6ksWPJg0skHMQB45I+GfF91aCPSDVOeyULYHwLbxkXLJsQmUOnK/u9F3pzN7vfzmQ2Jhi8GSXSd4csJteBUKFl/4f2iUwmyeO9leVkpVlwguQjpTGufOSBWzzegVIu4aES4TOWtetV/m/GZkMDINU8QceFqIgDlU7gTFl9MDWXT8s9IBUNVzgUNu3UUDkNb06frgmibpmBdr5+tcP9TwjeLiE6J4qiBbIjAYWvqncq8EWylKhJ6i43w1g0xRhAbTfNaP+p1cvMPmWPu9gfJuDWnwzpDn7sUmaX1AKf7FMGobnHOfsqj71+/rXu3CzKn
  template:
    metadata:
      name: authentik-secrets
      namespace: authentik
    type: Opaque
