---
fullnameOverride: "argocd"

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hostname: argocd.infra.beutra.fr
    tls: true
 
configs:
  cm:
    url: https://argocd.infra.beutra.fr
    oidc.config: |
      name: Authentik
      issuer: https://auth.beutra.fr/application/o/argocd/
      clientID: argocd
      clientSecret: $argocd-secret:oidc.authentik.clientSecret
      requestedScopes: ["openid", "profile", "email", "groups"]
 
  rbac:
    policy.default: ""
    policy.csv: |
      g, admins, role:admin
      g, admin, role:admin
 
      p, role:dev, applications, *, staging/*, allow
      p, role:dev, logs,         get, *, allow
      g, dev, role:dev
 
      p, role:guest, applications, get, epita/*, allow
      p, role:guest, applications, sync, epita/*, allow
      p, role:guest, logs,         get, epita/*, allow
      g, guest, role:guest
 
  params:
    server.insecure: "true"