---
fullnameOverride: "argocd"

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hostname: argocd.infra.beutra.fr
    tls: true
 
configs:
  cm:
    url: https://argocd.infra.beutra.fr
    oidc.config: |
      name: Keycloak
      issuer: https://keycloak.beutra.fr/realms/realm-pws
      clientID: argocd
      clientSecret: $argocd-keycloak-sso-secret:oidc.keycloak.clientSecret
      requestedScopes: ["openid", "profile", "email", "groups"]
      scopes: "[groups]"
 
  rbac:
    policy.default: ""
    policy.csv: |
      g, admins, role:admin
      g, admin, role:admin
 
      p, role:dev, applications, *, default/*, allow
      p, role:dev, applications, *, staging/*, allow
      p, role:dev, logs,         get, *, allow
      g, dev, role:dev
 
      p, role:guest, applications, get, default/*, allow
      p, role:guest, applications, get, staging/*, allow
      g, guest, role:guest
 
  params:
    server.insecure: "true"