apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tinyx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: epita
  sources:
    - repoURL: https://github.com/hugz6/petra-homelab-apps.git
      targetRevision: main
      path: argocd/apps/tinyx/deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: tinyx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
